language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
#install: "pip install pytest"
# command to run tests
script: py.test -vv --junit-xml=tests-result.xml
